[package]
name = "NftReveal"
version = "0.0.1"

[dependencies]
Sui = { local = "../../sui/crates/sui-framework" }
# NftProtocol = { local = "./nft-protocol" }


[dependencies.Movemate]
git = "https://github.com/Origin-Byte/movemate.git"
subdir = "sui"
# devnet-0.16.0
rev = "cfe98c1c87be8ece8f375c83aedddc028744fced"

# [dependencies.NftProtocol]
# git = "https://github.com/Origin-Byte/nft-protocol.git"
# # devnet-0.16.0
# rev = "cfe98c1c87be8ece8f375c83aedddc028744fced"

[addresses]
nft_reveal = "0x0"