[package]
name = "NftReveal"
version = "0.0.1"

[dependencies]
Sui = { local = "../../sui/crates/sui-framework" }


[dependencies.Movemate]
git = "https://github.com/LoyaltyGM/movemate.git"
subdir = "sui"
# devnet-0.18.0
rev = "2410981b1b667961be787a634e2708f062791de1"

[addresses]
nft_reveal = "0x0"