[package]
name = "NftReveal"
version = "0.0.1"

[dependencies]
Sui = { local = "../../sui/crates/sui-framework" }


[dependencies.Movemate]
git = "https://github.com/LoyaltyGM/movemate.git"
subdir = "sui"
# devnet-0.17.0
rev = "7cae189f568d2405b5f912eeabdcec9d19473a0a"

[addresses]
nft_reveal = "0x0"