[package]
name = "Tutorial"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../../sui/crates/sui-framework/deps/move-stdlib/" }
Sui = { local = "../../../sui/crates/sui-framework/" }

[addresses]
tutorial = "0x0"
