[package]
name = "LootBox"
version = "0.0.1"

[dependencies]
Sui = { local = "../../sui/crates/sui-framework" }

[dependencies.Movemate]
git = "https://github.com/LoyaltyGM/movemate.git"
subdir = "sui"
# devnet-0.19.0
rev = "ff31e6b3690341d9fde20e73a7afeb9636b9af1e"

[addresses]
lootbox = "0x0"